server:
  port: 5000

spring:
  application:
    name: eurekaServe

eureka:
  client:
    register-with-eureka: false # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: false   # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
  instance:
    lease-expiration-duration-in-seconds: 15
  #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
  server:
    eviction-interval-timer-in-ms: 5000
